### PR TITLE
Hopefully fixes the issue with incorrect aspect ratios for Favourites…

### PR DESCRIPTION
**Pull request by joethepartylion**
…. Slight issue is that if the icon has transparency then you can see the border image through it but that seems a small price to pay for now. Issue #4

### CODE REVIEW

**Comment by jester-xbmc** [comment]
Cheers

**Comment by Smultie** [comment]
Thanks, works like a charm!

**Comment by joethepartylion** [comment]
Hmm, looks like it may have caused an issue but waiting on some more info at the moment:

**http://forum.kodi.tv/showthread.php?tid=251260&pid=2281481#pid2281481**

**Comment by joethepartylion** [comment]
May have fixed it in #40

**Pull request merged**
