### PR TITLE
Latest round of updates

### PR DESCRIPTION
**Pull request by joethepartylion**
Disabling views seems to be working ok now, please test though.

### CODE REVIEW

**Comment by jester-xbmc** [comment]
Thanks, testing :)

**Comment by jester-xbmc** [comment]
addons seems indeed fixed, next up is the libreelec settings addon which is still missing the text and is complaining about the skin:
19:43:51 T:140350860850944 WARNING: CSkinInfo: failed to load skin settings
19:43:51 T:140352148830272 WARNING: Skin has invalid include: DefaultBackground
19:43:51 T:140352148830272 WARNING: Skin has invalid include: TopBar
19:43:51 T:140352148830272 WARNING: Skin has invalid include: BottomBar
19:43:51 T:140352148830272   ERROR: Window Translator: Can't find window videolibrary
19:43:51 T:140352148830272 WARNING: Label Formating: $VAR[GlobalFanartVar] is not defined
19:43:51 T:140352148830272   ERROR: Control 1000 in window 13001 has been asked to focus, but it can't

**Comment by jester-xbmc** [comment]
adding these fonts to font.xml fixes the text issue
font12
font24_title
font10
font13_title

But the backgrounds are still missing, per:
20:16:11 T:140496517175040 WARNING: CSkinInfo: failed to load skin settings
20:16:11 T:140497419565120 WARNING: Skin has invalid include: DefaultBackground
20:16:11 T:140497419565120 WARNING: Skin has invalid include: TopBar
20:16:11 T:140497419565120 WARNING: Skin has invalid include: BottomBar

**Comment by joethepartylion** [comment]
The easiest way to fix the missing includes is to copy the relevant text and media from confluence, maybe into a new include. Other option is to write our own version of the files, which is a bit more work

**Pull request merged**
