### PR TITLE
Krypton2

### PR DESCRIPTION
**Pull request by joethepartylion**
Not sure if you have been following the progress but I've added quite a few things in this pull.

Ability to toggle fanart on home and media screens
Allow backgrounds to follow into subwindows
Configurable TV, Radio entry points
New font option (5/5 trial)
Rework and standardise media views for panel, icons and lists

There is still some work to do on tidying up the media windows etc but generally I think It is good enough to go in but it's up to you if you like the new format or not.

### CODE REVIEW

**Comment by jester-xbmc** [comment]
Wow, thats some update, thanks for your work, i'm looking right now.

**Comment by joethepartylion** [comment]
Yes, I didn't know when to stop and just kept tweaking :-)

**Comment by joethepartylion** [comment]
Hi jester, I was just wondering if you had managed to review this yet?
I've kept plugging away and I've now reworked the shelves to add more options and remove the requirement for Skin widgets, this is in my Krypton3 branch and with the alpha coming soon I'd like to get it into the repo if possible to get as much feedback as we can.

**Comment by jester-xbmc** [comment]
Hi, im traveling for work, i should be done reviewing and merging this weekend

**Pull request merged**
