### PR TITLE
Consistency and standardisation updates, plus a few new features

### PR DESCRIPTION
**Pull request by joethepartylion**
Dialog updates
PVR Updates
Media clean up
Addon window updates
Test for disabling library view types (only for video library currently)
Other tweaks

### CODE REVIEW

**Comment by jester-xbmc** [comment]
Thanks i'm having a look over the weekend, did you catch this comment by the kodi guys by any chance ?

log file errors:
T:10892 WARNING: Skin has invalid include:
T:4500 WARNING: Previous line repeats 50 times.
comment from kodi dev: Basically that's because some of the ShelfSubList includes are invalid if there are less than 5 sublists defined

**Comment by joethepartylion** [comment]
No I hadn't seen that one, I wonder what can be done, maybe a default dummy include may work.

I'm off on holiday for a week now but I'll have a look when I get back in August.

On 21 Jul 2016, at 17:01, Jester <notifications@github.com<mailto:notifications@github.com>> wrote:

Thanks i'm having a look over the weekend, did you catch this comment by the kodi guys by any chance ?

log file errors:
T:10892 WARNING: Skin has invalid include:
T:4500 WARNING: Previous line repeats 50 times.
comment from kodi dev: Basically that's because some of the ShelfSubList includes are invalid if there are less than 5 sublists defined

##

**Comment by jester-xbmc** [comment]
Cheers, enjoy your holidays, I'll have a stab at it over the weekend

**Comment by joethepartylion** [comment]
Warnings are fixed in this commit 934d8d574705dd051e4ec88c50ebfc431cdef211

**Comment by jester-xbmc** [comment]
Thanks, however I pulled in some of your updates and just wanted to push them to the repo but upon testing things are missing/not working:
under kodi settings under player setting there is a blank line where it should read Library settings, the libreelec settings screen is missing text and launching add-ons from the shelve makes the navigation within the selve stop working....
debugging now....

**Comment by joethepartylion** [comment]
My Krypton5 branch is based on the latest nightlies and Library Settings has been renamed Media Settings hence the missing item if you are still on earlier release.

I'll have a look at the addons issue tomorrow if I get a chance and libreelec may be because it has hard coded font names that we don't use.

**Comment by joethepartylion** [comment]
I would revert the commit for disabling views as I think it needs to be done a different way, I'm thinking of a select dialog to choose the view which will hide those that are disabled. That should avoid the issues we have. I'll have a look at the libreelec code to see what fonts it uses.

**Comment by joethepartylion** [comment]
Libreelec uses these fonts which we don't have defined

font12
font24_title
font10
font13_title

I'll see if I can have a look at it tomorrow, my dev machine is inaccessible atm.

**Comment by jester-xbmc** [comment]
True, but we didn't include them in 3.0.2 either and its works fine there, did I miss a font removal somewhere?

**Comment by joethepartylion** [comment]
No there weren't any recent font changes, seems very odd.

I've just uploaded a new version of the view disabling work if you want to take a peek 1d69c906c3ea90f09ea33e273bf5cbfcec03b279

**Comment by jester-xbmc** [comment]
I'll have a look, i'm trying to get my head around the add-on shelf issue, once you add an addon to the home-shelf (under favorites) it launches but navigation stops work, except exit/return, when you launch it from the add-on home shelf under video (youtube for example) it works fine, but log file on exit gives: 2:00:58 631.145691 T:140275291420416   ERROR: Unable to find plugin
12:00:58 631.145752 T:140275310356544   ERROR: GetDirectory - Error getting plugin://
12:00:58 631.145874 T:140275310356544   ERROR: CGUIMediaWindow::GetDirectory(plugin://) failed

Something hinky is going on....

**Comment by jester-xbmc** [comment]
the libreeec seetings addon btw = 12:05:58 931.107300 T:140275291420416 WARNING: CSkinInfo: failed to load skin settings
12:05:58 931.131042 T:140275310356544 WARNING: Skin has invalid include: DefaultBackground
12:05:58 931.131042 T:140275310356544 WARNING: Skin has invalid include: TopBar
12:05:58 931.131042 T:140275310356544 WARNING: Skin has invalid include: BottomBar
12:05:58 931.132751 T:140275310356544   ERROR: Window Translator: Can't find window videolibrary
12:05:58 931.132874 T:140275310356544 WARNING: Label Formating: $VAR[GlobalFanartVar] is not defined
12:05:58 931.150146 T:140275310356544   ERROR: Control 1000 in window 13001 has been asked to focus, but it can't

**Comment by joethepartylion** [comment]
I wonder if the addons issue is related to 9a433737f241660a4fc3c06ed112936efe2ddbb1

I'm testing the new view options which should fix that as I can;t reproduce it on my machine, addons from favorites work fine for me.

**Pull request merged**
