### PR TITLE
Completely reworked VideoOSD for Movies, PVR, Episodes and Music Videos.

### PR DESCRIPTION
**Pull request by joethepartylion**
Hi Jester, I've had a go at reworking the Video OSD files to make them more consistent. Let me know what you think.

### CODE REVIEW

**Comment by joethepartylion** [comment]
Hi Jester, this seems to be working well so far as per http://forum.kodi.tv/showthread.php?tid=256862&pid=2231368#pid2231368

Are you happy for this to go in or would you like any changes?

**Comment by jester-xbmc** [comment]
I had a quick peek, looks good, thanks for the work, i'll have a proper look tomorrow and probably merge the same day :)

**Comment by joethepartylion** [comment]
No problem, thanks for having a look. The next thing to change would be the seekbar as we are now duplicating info in both locations, but that can wait for another day :-)

**Comment by jester-xbmc** [comment]
Nice work, thanks

**Pull request merged**
